### ISSUE TITLE
I can't create a account

### ISSUE THREAD

**Issue by Bomface1122** [TheDucky/DuckID#3]
I click login and i takes me to discord
i accepted then it takes me bac to login
and it dose not create a account for me

**Comment by bryan-ente** [comment]
Hey, did you follow each step? If yes, does Discord show you any errors?

**Comment by Bomface1122** [comment]
i get a error in the website log
but not any from discord

Got error 'PHP message: PHP Notice: Undefined index: access_token in api/inc/db.inc.php on line 26PHP message: PHP Notice: Undefined index: log_checkid in api/handling/login.php on line 9'.

**Comment by bryan-ente** [comment]
Everything needs to work properly.
If you followed each step and cloned the normal Repo and not the release, then your Discord Redirect for the Auth should be like this: http://[IP or Domain].[tld]/api/handling/discord_login.php?discord=true

Could you check, that your redirect is like this?

But please also keep in mind, that the software is still in development!

**Comment by Bomface1122** [comment]
Ok that worked
probably should add that in the docs
as i just has the redirect to my domain

**Comment by bryan-ente** [comment]
I know, I am sorry for that!
