### ISSUE TITLE
No Ticket submit button

### ISSUE THREAD

**Issue by Bomface1122** [TheDucky/DuckID#4]
**Is your feature request related to a problem? Please describe.**
The website is about ticket system, so not being able to create a ticket makes the website useless 

**Describe the solution you'd like**
A way to submit a ticket

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by bryan-ente** [comment]
Hey,

currently there's no "Create Ticket"-Button, but you can also navigate to the `api/handling/actions/tickets/create_ticket.php`
to create a ticket, but please read the script before, to understand which variables need to be passed.

The (local) development branch already has the "Create-Ticket"-Button feature and it will be implemented very soon.
